* Lab 3: Consuming and Processing Events

*Objective:* Solidify the concepts of events, event signal URLs (ESLs), and registration. Become familiar with Foursquare's Real-Time API.

* Delivery Driver website

- Build an event consumer to listen for and process Foursquare "events"
- Store on your server information about the last checkin
- Create multiple, unique Event Signal URLs (ESLs) for each flower shop the driver wants to deliver for
  - The driver will associate these ESLs with the ones received from the individual flower shops during the registration process.
- Respond to /bid_needed/ events as follows:
  - If the driver is within /n/ miles of the flower shop, submit a bid automatically to the flower shop and send the driver an SMS notification about the details of the bid.
  - If the bid can't be processed automatically, send the driver an SMS. If the driver responds to the SMS with "bid anyway", submit a bid to the flower shop.
- Submit bids by signaling a /bid_available/ event to the flower shop's ESL.

* Foursquare Real-Time API

You will use the Foursquare Real-Time API to receive the driver's location updates. It is documented here: https://developer.foursquare.com/overview/realtime

A few things to keep in mind:

- Your system must support SSL
- You will give Foursquare a URL to your server, which acts as the event consumer for Foursquare
  - This consumer will receive the driver's location updates from Foursquare and store them on your server.

* Signaling events

You will be signaling one event in this lab. The event domain and name must be the following:
- Event domain: *rfq*
- Event name: *bid_available*

That event will need several attributes, such as the following:
- Driver name
- Estimated arrival time

* Passing off

Passoff process TBD. Will require at least a code review.

Items needed for the review:
- A screenshot of your app's registration page from https://foursquare.com/oauth
- A copy of all the code for your delivery driver website
- Any explanation necessary to understand the structure or behavior of your code

* Grading

- Proper registration with Foursquare Real-Time API, including SSL support: 15%
- Foursquare "events" properly received and stored: 25%
- Driver website produces unique ESLs for each flower shop and stores the ESL received from the flower shop: 25%
- Proper /bid_available/ event signaling: 35%

